[workspace]
authors = ["Stanley5249 <seer852741@gmail.com>"]
channels = ["https://prefix.dev/conda-forge"]
platforms = ["linux-64", "osx-64", "win-64"]
preview = ["pixi-build"]

[workspace.target.win.build-variants]
c_compiler = ["vs2022"]
cxx_compiler = ["vs2022"]

[tasks]

[dependencies]
ebnn-host = { path = "." }

[package]
name = "ebnn-host"
version = "0.1.0"

[package.build.backend]
channel = "https://prefix.dev/conda-forge"
name = "pixi-build-cmake"
version = "*"

[package.build.config]
extra-args = ["-DBUILD_SHARED_LIBS=OFF"]

[package.host-dependencies]
glad2 = ">=2.0.8,<3"
glad2-cmake = ">=2.0.8,<3"
imgui = ">=1.92.1,<2"
libvulkan-headers = ">=1.4.313.0,<2"
libvulkan-loader = ">=1.4.313.0,<2"
